apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        kind: build
        shell: sh
        run: echo 'hello'
      - uses: cloudbees-io/github-security-sast-scan-code@v1
        name: Security sast
        kind: build
        with:
          token: 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
